from typing import Literal, Optional, Union

from flax.struct import dataclass

from agents import CRL, PPO, SAC, TD3

from .env import legal_envs

# agent configurations
AgentConfig = Union[CRL, PPO, SAC, TD3]


@dataclass
class RunConfig:
    """General run configs
    Args:
        seed: random seed
        env_name: the name of the environment to use
        total_env_steps: the total number of environment steps to run
        episode_length: the maximum length of an episode
            NOTE: `num_envs * (episode_length - 1)` must be divisible by
            `batch_size` due to the way data is stored in replay buffer.
        num_envs: the number of parallel environments to use for rollouts
            NOTE: `num_envs` must be divisible by the total number of chips since each
            chip gets `num_envs // total_number_of_chips` environments to roll out
            NOTE: `batch_size * num_minibatches` must be divisible by `num_envs` since
            data generated by `num_envs` parallel envs gets used for gradient
            updates over `num_minibatches` of data, where each minibatch has a
            leading dimension of `batch_size`
        max_devices_per_host: maximum number of chips to use per host process
        num_eval_envs: the number of envs to use for evluation. Each env will run 1
        episode, and all envs run in parallel during eval.
        action_repeat: the number of timesteps to repeat an action
        exp_name: the name of the experiment for logging
        num_evals: the number of evals to run during the entire training run.
            Increasing the number of evals increases total training time
    """

    env: Literal[tuple(legal_envs)]
    total_env_steps: int = 1_000_000
    episode_length: int = 1001
    eval_env: Optional[Literal[tuple(legal_envs)]] = None
    num_envs: int = 128
    num_eval_envs: int = 128
    action_repeat: int = 1
    num_evals: int = 50

    seed: int = 0
    exp_name: str = "run"
    backend: Optional[Literal["mjx", "spring", "positional", "generalized"]] = None
    log_wandb: bool = True
    wandb_project_name: str = "jaxgcrl"
    # online or offline
    wandb_mode: Literal["online", "offline"] = "online"
    wandb_group: str = "."
    checkpoint: bool = False
    visualization_interval: int = 5
    vis_length: int = 1000
    checkpoint_logdir: Optional[str] = None
    max_devices_per_host: int = 1
    cuda: bool = True


@dataclass
class Config:
    # agent type
    agent: AgentConfig
    # run config
    run: RunConfig
